/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package fixtures.subscriptionidapiversion.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SampleResourceGroupInner model.
 */
public class SampleResourceGroupInner {
    /**
     * resource group name 'testgroup101'.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * resource group location 'West US'.
     */
    @JsonProperty(value = "location")
    private String location;

    /**
     * Get resource group name 'testgroup101'.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set resource group name 'testgroup101'.
     *
     * @param name the name value to set
     * @return the SampleResourceGroupInner object itself.
     */
    public SampleResourceGroupInner withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get resource group location 'West US'.
     *
     * @return the location value
     */
    public String location() {
        return this.location;
    }

    /**
     * Set resource group location 'West US'.
     *
     * @param location the location value to set
     * @return the SampleResourceGroupInner object itself.
     */
    public SampleResourceGroupInner withLocation(String location) {
        this.location = location;
        return this;
    }

}
