// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

package fixtures.bodydatetime.implementation;

import com.azure.core.http.HttpPipeline;
import com.azure.core.implementation.RestProxy;
import com.azure.core.implementation.annotation.ServiceClientBuilder;
import fixtures.bodydatetime.AutoRestDateTimeTestService;
import fixtures.bodydatetime.Datetimes;

/**
 * A builder for creating a new instance of the AutoRestDateTimeTestService type.
 */
@ServiceClientBuilder(serviceClients = AutoRestDateTimeTestService.class)
public final class AutoRestDateTimeTestServiceBuilder {
    /*
     * The HTTP pipeline to send requests through
     */
    private HttpPipeline pipeline;

    /**
     * Sets The HTTP pipeline to send requests through.
     *
     * @param pipeline the pipeline value.
     * @return the AutoRestDateTimeTestServiceBuilder.
     */
    public AutoRestDateTimeTestServiceBuilder pipeline(HttpPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }

    /**
     * Builds an instance of AutoRestDateTimeTestService with the provided parameters.
     *
     * @return an instance of AutoRestDateTimeTestService.
     */
    public AutoRestDateTimeTestService build() {
        if (pipeline == null) {
            this.pipeline = RestProxy.createDefaultPipeline();
        }
        AutoRestDateTimeTestServiceImpl client = new AutoRestDateTimeTestServiceImpl(pipeline);
        return client;
    }
}
