echo "Autorest"
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.parameterflattening --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/parameter-flattening.json --use=/Users/abandy/Documents/GitHub/autorest.java

AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyarray --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-array.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyboolean --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-boolean.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodycomplex --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-complex.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodydate --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-date.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodydatetime --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-datetime.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodydatetimerfc1123 --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-datetime-rfc1123.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyduration --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-duration.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodydictionary --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-dictionary.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyfile --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-file.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyformdata --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-formdata.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodyinteger --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-integer.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodynumber --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-number.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodystring --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-string.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.header --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/header.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.http --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/httpInfrastructure.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.report --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/report.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.requiredoptional --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/required-optional.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.url --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/url.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.validation --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/validation.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.custombaseuri --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/custom-baseUrl.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.custombaseurimoreoptions --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/custom-baseUrl-more-options.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/vanilla --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.modelflattening --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/model-flattening.json --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.lro --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/lro.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.paging --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/paging.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azurereport --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-report.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azureparametergrouping --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-parameter-grouping.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azureresource --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-resource.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.head --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/head.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.headexceptions --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/head-exceptions.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.subscriptionidapiversion --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/subscriptionId-apiVersion.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azurespecials --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-special-properties.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azure --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.custombaseuri --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/custom-baseUrl.json --java.azure-arm=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.lro --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/lro.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.paging --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/paging.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azurereport --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-report.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azureparametergrouping --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-parameter-grouping.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azureresource --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-resource.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.head --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/head.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.headexceptions --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/head-exceptions.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.subscriptionidapiversion --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/subscriptionId-apiVersion.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.azurespecials --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/azure-special-properties.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/azurefluent --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.custombaseuri --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/custom-baseUrl.json --java.azure-arm=true --java.fluent=true --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/nonnull --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.non-null-annotations=false --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/clienttypeprefix --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.client-type-prefix=zzz --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/generateclientinterfaces --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.generate-client-interfaces=false --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/implementationsubpackage --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.implementation-subpackage=spam --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/implementationsubpackage-empty --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.implementation-subpackage='' --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/modelssubpackage --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.models-subpackage=spam --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/modelssubpackage-empty --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.bodybyte --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/body-byte.json --java.models-subpackage='' --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/requiredparameterclientmethods-false --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.requiredoptional --input-file=node_modules/@microsoft.azure/autorest.testserver/swagger/required-optional.json --java.required-parameter-client-methods=false --use=/Users/abandy/Documents/GitHub/autorest.java
AutoRest --java --output-folder=test/xml --license-header=MICROSOFT_MIT_NO_VERSION --java.namespace=Fixtures.xml --input-file=test/swagger/xml-service.json --enable-xml=true --use=/Users/abandy/Documents/GitHub/autorest.java
