// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.type.property.nullable.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.type.property.nullable.implementation.JsonMergePatchHelper;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Model with a datetime property.
 */
@Immutable
public final class DatetimeProperty {
    /*
     * Required property
     */
    @Generated
    @JsonProperty(value = "requiredProperty")
    private String requiredProperty;

    /*
     * Property
     */
    @Generated
    @JsonProperty(value = "nullableProperty")
    private OffsetDateTime nullableProperty;

    @Generated
    private boolean jsonMergePatch;

    @Generated
    private final Set<String> updatedProperties = new HashSet<>();

    @Generated
    void serializeAsJmp(boolean jsonMergePatch) {
        this.jsonMergePatch = jsonMergePatch;
    }

    static {
        JsonMergePatchHelper.setDatetimePropertyAccessor((model, jsonMergePatchEnabled) -> {
            model.serializeAsJmp(jsonMergePatchEnabled);
            return model;
        });
    }

    /**
     * Creates an instance of DatetimeProperty class.
     * 
     * @param requiredProperty the requiredProperty value to set.
     * @param nullableProperty the nullableProperty value to set.
     */
    @Generated
    @JsonCreator
    public DatetimeProperty(@JsonProperty(value = "requiredProperty") String requiredProperty,
        @JsonProperty(value = "nullableProperty") OffsetDateTime nullableProperty) {
        this.requiredProperty = requiredProperty;
        this.nullableProperty = nullableProperty;
    }

    /**
     * Get the requiredProperty property: Required property.
     * 
     * @return the requiredProperty value.
     */
    @Generated
    public String getRequiredProperty() {
        return this.requiredProperty;
    }

    /**
     * Get the nullableProperty property: Property.
     * 
     * @return the nullableProperty value.
     */
    @Generated
    public OffsetDateTime getNullableProperty() {
        return this.nullableProperty;
    }
}
