// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com._specs_.azure.core.basic.models;

import com._specs_.azure.core.basic.implementation.JsonMergePatchHelper;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;

import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

import java.util.HashSet;

import java.util.Set;

/**
 * UserOrder for testing list with expand.
 */
@Immutable
public final class UserOrder implements JsonSerializable<UserOrder> {
    /*
     * The user's id.
     */
    @Generated
    private int id;

    /*
     * The user's id.
     */
    @Generated
    private final int userId;

    /*
     * The user's order detail
     */
    @Generated
    private final String detail;

    @Generated
    private boolean jsonMergePatch;

    /**
     * Stores updated model property, the value is property name, not serialized name.
     */
    @Generated
    private final Set<String> updatedProperties = new HashSet<>();

    @Generated
    void serializeAsJsonMergePatch(boolean jsonMergePatch) {
        this.jsonMergePatch = jsonMergePatch;
    }

    static {
        JsonMergePatchHelper.setUserOrderAccessor((model, jsonMergePatchEnabled) -> {
            model.serializeAsJsonMergePatch(jsonMergePatchEnabled);
            return model;
        });
    }

    /**
     * Creates an instance of UserOrder class.
     * 
     * @param userId the userId value to set.
     * @param detail the detail value to set.
     */
    @Generated
    public UserOrder(int userId, String detail) {
        this.userId = userId;
        this.detail = detail;
    }

    /**
     * Get the id property: The user's id.
     * 
     * @return the id value.
     */
    @Generated
    public int getId() {
        return this.id;
    }

    /**
     * Get the userId property: The user's id.
     * 
     * @return the userId value.
     */
    @Generated
    public int getUserId() {
        return this.userId;
    }

    /**
     * Get the detail property: The user's order detail.
     * 
     * @return the detail value.
     */
    @Generated
    public String getDetail() {
        return this.detail;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        if (jsonMergePatch) {
            return toJsonMergePatch(jsonWriter);
        } else {
            jsonWriter.writeStartObject();
            jsonWriter.writeIntField("userId", this.userId);
            jsonWriter.writeStringField("detail", this.detail);
            return jsonWriter.writeEndObject();
        }
    }

    public JsonWriter toJsonMergePatch(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeIntField("userId", this.userId);
        if (this.detail != null) {
            jsonWriter.writeStringField("detail", this.detail);
        } else if (updatedProperties.contains("detail")) {
            jsonWriter.writeNullField("detail");
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of UserOrder from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of UserOrder if the JsonReader was pointing to an instance of it, or null if it was pointing
     * to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the UserOrder.
     */
    public static UserOrder fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            int id = 0;
            int userId = 0;
            String detail = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    id = reader.getInt();
                } else if ("userId".equals(fieldName)) {
                    userId = reader.getInt();
                } else if ("detail".equals(fieldName)) {
                    detail = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            UserOrder deserializedUserOrder = new UserOrder(userId, detail);
            deserializedUserOrder.id = id;

            return deserializedUserOrder;
        });
    }
}
