// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the data models for AutoRestParameterizedCustomHostTestClient. Test Infrastructure for AutoRest.
 */
package fixtures.custombaseuri.moreoptions.models;
