emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/tsp-output"
    generate-samples: true
    generate-tests: false
    dev-options:
      generate-code-model: true
      support-versioning: true
      loglevel: info
