// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.parameters.spread.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Options for spreadWithMultipleParameters API. */
@Immutable
public final class SpreadWithMultipleParametersOptions {
    /*
     * The id property.
     */
    @Generated
    @JsonProperty(value = "id")
    private String id;

    /*
     * The x-ms-test-header property.
     */
    @Generated
    @JsonProperty(value = "x-ms-test-header")
    private String xMsTestHeader;

    /*
     * The prop1 property.
     */
    @Generated
    @JsonProperty(value = "prop1")
    private String prop1;

    /*
     * The prop2 property.
     */
    @Generated
    @JsonProperty(value = "prop2")
    private String prop2;

    /*
     * The prop3 property.
     */
    @Generated
    @JsonProperty(value = "prop3")
    private String prop3;

    /*
     * The prop4 property.
     */
    @Generated
    @JsonProperty(value = "prop4")
    private String prop4;

    /*
     * The prop5 property.
     */
    @Generated
    @JsonProperty(value = "prop5")
    private String prop5;

    /*
     * The prop6 property.
     */
    @Generated
    @JsonProperty(value = "prop6")
    private String prop6;

    /**
     * Creates an instance of SpreadWithMultipleParametersOptions class.
     *
     * @param id the id value to set.
     * @param xMsTestHeader the xMsTestHeader value to set.
     * @param prop1 the prop1 value to set.
     * @param prop2 the prop2 value to set.
     * @param prop3 the prop3 value to set.
     * @param prop4 the prop4 value to set.
     * @param prop5 the prop5 value to set.
     * @param prop6 the prop6 value to set.
     */
    @Generated
    @JsonCreator
    public SpreadWithMultipleParametersOptions(
            @JsonProperty(value = "id") String id,
            @JsonProperty(value = "x-ms-test-header") String xMsTestHeader,
            @JsonProperty(value = "prop1") String prop1,
            @JsonProperty(value = "prop2") String prop2,
            @JsonProperty(value = "prop3") String prop3,
            @JsonProperty(value = "prop4") String prop4,
            @JsonProperty(value = "prop5") String prop5,
            @JsonProperty(value = "prop6") String prop6) {
        this.id = id;
        this.xMsTestHeader = xMsTestHeader;
        this.prop1 = prop1;
        this.prop2 = prop2;
        this.prop3 = prop3;
        this.prop4 = prop4;
        this.prop5 = prop5;
        this.prop6 = prop6;
    }

    /**
     * Get the id property: The id property.
     *
     * @return the id value.
     */
    @Generated
    public String getId() {
        return this.id;
    }

    /**
     * Get the xMsTestHeader property: The x-ms-test-header property.
     *
     * @return the xMsTestHeader value.
     */
    @Generated
    public String getXMsTestHeader() {
        return this.xMsTestHeader;
    }

    /**
     * Get the prop1 property: The prop1 property.
     *
     * @return the prop1 value.
     */
    @Generated
    public String getProp1() {
        return this.prop1;
    }

    /**
     * Get the prop2 property: The prop2 property.
     *
     * @return the prop2 value.
     */
    @Generated
    public String getProp2() {
        return this.prop2;
    }

    /**
     * Get the prop3 property: The prop3 property.
     *
     * @return the prop3 value.
     */
    @Generated
    public String getProp3() {
        return this.prop3;
    }

    /**
     * Get the prop4 property: The prop4 property.
     *
     * @return the prop4 value.
     */
    @Generated
    public String getProp4() {
        return this.prop4;
    }

    /**
     * Get the prop5 property: The prop5 property.
     *
     * @return the prop5 value.
     */
    @Generated
    public String getProp5() {
        return this.prop5;
    }

    /**
     * Get the prop6 property: The prop6 property.
     *
     * @return the prop6 value.
     */
    @Generated
    public String getProp6() {
        return this.prop6;
    }
}
