trigger: none
pr: none

parameters:
- name: SubmodulePullRequestId
  displayName: 'Pull Request ID of the Submodule'
  type: string

jobs:
- template: /eng/pipelines/jobs/build-autorest.yml
  parameters:
    SubmodulePullRequestId: ${{ parameters.SubmodulePullRequestId }}
- template: /eng/pipelines/jobs/build-autorest-mgmt.yml
  parameters:
    SubmodulePullRequestId: ${{ parameters.SubmodulePullRequestId }}
- template: /eng/pipelines/jobs/build-typespec.yml
  parameters:
    SubmodulePullRequestId: ${{ parameters.SubmodulePullRequestId }}
