trigger: none
pr: none

parameters:
- name: SubmoduleCommit
  displayName: 'Commit ID of the Submodule'
  type: string

jobs:
- template: /eng/pipelines/jobs/build-autorest.yml
  parameters:
    SubmoduleCommit: ${{ parameters.SubmoduleCommit }}
- template: /eng/pipelines/jobs/build-autorest-mgmt.yml
  parameters:
    SubmoduleCommit: ${{ parameters.SubmoduleCommit }}
- template: /eng/pipelines/jobs/build-typespec.yml
  parameters:
    SubmoduleCommit: ${{ parameters.SubmoduleCommit }}
