trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'androidgen'
      - 'azure-dataplane-tests'
      - 'azure-tests'
      - 'fluent-tests'
      - 'partial-update-tests'
      - 'vanilla-tests'
      - 'protocol*'

jobs:
  - job: Build

    timeoutInMinutes: 30

    variables:
      - template: /eng/pipelines/variables/globals.yml
      - name: isMain
        value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

    pool:
      name: "azsdk-pool-mms-ubuntu-2004-general"
      vmImage: "MMSUbuntu20.04"

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - template: /eng/pipelines/steps/cache-maven-repository.yml
        parameters:
          JobType: 'TypeSpec'

      - task: Maven@3
        displayName: 'Build JAR'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean install'
          options: '$(DefaultOptions) -P local,tsp -T 1C'
          mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PowerShell@2
        retryCountOnTaskFailure: 1
        displayName: 'Generate Code'
        inputs:
          pwsh: true
          filePath: Generate-TypeSpec.ps1
          arguments: '-Parallelization 1'

      - script: |
          git status
          git diff
        displayName: 'Git Diff'

      - script: |
          [ -z "`git status --porcelain -- :!package-lock.json`" ]
        displayName: 'Check no Diff'

      - script: |
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js serve node_modules/\@azure-tools/cadl-ranch-specs/http/ --coverageFile ./cadl-ranch-coverage-java.json &
        displayName: 'Start Cadl Ranch Test Server'
        workingDirectory: ./typespec-tests

      - task: Maven@3
        displayName: 'Run TypeSpec Tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '$(DefaultOptions) -PtestTsp -pl typespec-tests -DtrimStackTrace=false'
          mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js server stop
        displayName: 'Stop Cadl Ranch Test Server'
        workingDirectory: ./typespec-tests

      - script: |
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js check-coverage node_modules/@azure-tools/cadl-ranch-specs/http --coverageFiles ./cadl-ranch-coverage-java.json
        displayName: 'Cadl Ranch Coverage Report'
        workingDirectory: ./typespec-tests
        continueOnError: true

      - publish: $(Build.SourcesDirectory)/typespec-tests/cadl-ranch-coverage-java.json
        artifact: CoverageReport
        displayName: 'Publish Cadl Ranch Coverage Report'

      - task: AzureCLI@2
        displayName: 'Upload to Cadl Ranch Coverage Report Dashboard'
        condition: eq(variables.isMain, 'true')
        inputs:
          azureSubscription: "Cadl Ranch Storage"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: node $(Build.SourcesDirectory)/typespec-tests/node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js upload-coverage --coverageFile $(Build.SourcesDirectory)/typespec-tests/cadl-ranch-coverage-java.json --generatorName java --storageAccountName azuresdkcadlranch --generatorMode azure --generatorVersion $(node -p -e "require('./typespec-extension/package.json').version")

      - template: /eng/pipelines/steps/cleanup-maven-local-cache.yml
