trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'azure-dataplane-tests'
      - 'azure-tests'
      - 'fluent-tests'
      - 'partial-update-tests'
      - 'vanilla-tests'
      - 'protocol*'

jobs:
- template: /eng/pipelines/jobs/build-typespec.yml
