trigger:
  branches:
    include:
    - v4
    - main

pr:
  branches:
    include:
    - v4
    - main

jobs:
  - job: Build

    variables:
      JavaVersion: 1.8
      NodeVersion: '12.x'

    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - task: Maven@3
        displayName: 'Build and Package'
        inputs:
          mavenPomFile: pom.xml
          goals: 'install package'
          options: '-Dlocal'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          npm install -g autorest
          npm install --no-bin-links
        displayName: 'Prepare Environment for Generation'

      - script: |
          ./generate
        displayName: 'Generate code'

      - script: |
          git diff
        displayName: 'Git Diff'

      - script: |
          [ -z "`git status --porcelain`" ]
        displayName: 'Check no diff in generated files'

      - task: Maven@3
        displayName: 'Run vanilla tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'test'
          options: '-DtestVanilla -pl vanilla-tests'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: Maven@3
        displayName: 'Run azure tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'test'
          options: '-DtestAzure -pl azure-tests'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

#      - script: |
#          cp coverage/* node_modules/@microsoft.azure/autorest.testserver/legacy/coverage/
#        displayName: 'Copy coverage report'

      - script: |
          npm run coverage-push -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
        workingDirectory: node_modules/@microsoft.azure/autorest.testserver
        displayName: 'Publish coverage report to storage account'
