trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'fluent*'
      - 'typespec*'

jobs:
  - job: Build

    timeoutInMinutes: 60

    variables:
      JavaVersion: 1.11
      NodeVersion: '18.x'

    pool:
      name: "azsdk-pool-mms-ubuntu-2004-general"
      vmImage: "MMSUbuntu20.04"

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - task: Maven@3
        retryCountOnTaskFailure: 3
        displayName: 'Build and Package'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean verify package install'
          options: '-P local -T 1C --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          npm install -g autorest
          npm install
        displayName: 'Prepare Environment for Generation'

      - task: PowerShell@2
        displayName: 'Generate Code'
        inputs:
          pwsh: true
          filePath: Generate.ps1

      - script: |
          git status
          git diff
        displayName: 'Git Diff'

      - script: |
          [ -z "`git status --porcelain`" ]
        displayName: 'Check no Diff'

      - script: |
          npm run testserver-run &
        displayName: 'Start Testserver'

      - task: Maven@3
        displayName: 'Run Vanilla Tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-DtestVanilla -pl vanilla-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        inputs:
          mergeTestResults: true
          testRunTitle: 'vanilla-tests'
          searchFolder: '$(System.DefaultWorkingDirectory)/vanilla-tests/'

      - task: Maven@3
        displayName: 'Run Azure Tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-DtestAzure -pl azure-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        inputs:
          mergeTestResults: true
          testRunTitle: 'azure-tests'
          searchFolder: '$(System.DefaultWorkingDirectory)/azure-tests/'

      - task: Maven@3
        displayName: 'Run Protocol Tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-DtestProtocol -pl protocol-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        inputs:
          mergeTestResults: true
          testRunTitle: 'protocol-tests'
          searchFolder: '$(System.DefaultWorkingDirectory)/protocol-tests/'

      - script: |
          npm run testserver-stop
        displayName: 'Stop Testserver'

      - script: |
          cat coverage/report-vanilla.json || true
          cat coverage/report-azure.json || true
          cat coverage/report-dpg.json || true
        displayName: 'Display Coverage Data'

      - script: |
          npm run testserver-coverage-publish -- --repo=$(Build.Repository.Name) --ref=$(Build.SourceBranch) --githubToken=$(github-token) --azStorageAccount=$(storage-coverage-user) --azStorageAccessKey=$(storage-coverage-pass)
        condition: and(succeeded(), ne(variables['storage-coverage-pass'], ''))
        displayName: 'Publish Coverage Report'

      - task: Maven@3
        displayName: 'Verify Javadoc of Protocol Tests'
        inputs:
          mavenPomFile: protocol-tests/pom.xml
          goals: 'javadoc:javadoc'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: Maven@3
        displayName: 'Run Protocol Resilience Tests'
        inputs:
          mavenPomFile: protocol-resilience-test/pom.xml
          goals: 'package revapi:check'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          ./protocol-sdk-integration-tests/test.py
        displayName: 'Run Protocol Test on SDK Integration'
