trigger:
  branches:
    include:
    - v4
    - main
    - llc

pr:
  branches:
    include:
    - v4
    - main
    - llc

jobs:
  - job: Build

    variables:
      JavaVersion: 1.8
      NodeVersion: '14.x'

    pool:
      vmImage: ubuntu-latest

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - task: Maven@3
        displayName: 'Build and Package'
        inputs:
          mavenPomFile: pom.xml
          goals: 'install package'
          options: '-Dlocal -T 1C --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - script: |
          npm install -g autorest
          npm install --no-bin-links
        displayName: 'Prepare Environment for Generation'

      - script: |
          ./generate
        displayName: 'Generate code'

      - script: |
          git diff
        displayName: 'Git Diff'

      - script: |
          [ -z "`git status --porcelain`" ]
        displayName: 'Check no diff in generated files'

      - task: Maven@3
        displayName: 'Run vanilla tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-DtestVanilla -pl vanilla-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          mergeTestResults: true
          testRunTitle: 'vanilla-tests'
          searchFolder: '$(System.DefaultWorkingDirectory)/vanilla-tests/'

      - task: Maven@3
        displayName: 'Run azure tests'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean test'
          options: '-DtestAzure -pl azure-tests -DtrimStackTrace=false --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          mergeTestResults: true
          testRunTitle: 'azure-tests'
          searchFolder: '$(System.DefaultWorkingDirectory)/azure-tests/'

      - script: |
          npm --prefix node_modules/@microsoft.azure/autorest.testserver run coverage publish -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
        displayName: 'Publish coverage report to storage account'
