trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main
  paths:
    include:
      - '*'
    exclude:
      - 'cadl*'

jobs:
- job: 'Build'
  timeoutInMinutes: 60
  pool:
    name: azsdk-pool-mms-win-2022-general
    vmImage: windows-2022

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: npm install autorest -g

  - task: Maven@3
    retryCountOnTaskFailure: 1
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'verify'
      options: '-P local,testFluent --no-transfer-progress'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: fluentgen/target/site/test-coverage/jacoco.xml
      reportDirectory: fluentgen/target/site/test-coverage/
      failIfCoverageEmpty: false
