trigger:
  branches:
    include:
    - v4*
    - main

pr:
  branches:
    include:
    - v4
    - main

jobs:
- job: 'Build'
  timeoutInMinutes: 20
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=14.0.0'

  - script: npm install autorest -g

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'verify'
      options: '-P local,testFluent --no-transfer-progress'
