trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - '*'
    exclude:
      - 'typespec*'

jobs:
- job: 'Build'
  timeoutInMinutes: 60
  pool:
    name: "azsdk-pool-mms-ubuntu-2004-general"
    vmImage: "MMSUbuntu20.04"

  variables:
    - template: /eng/pipelines/variables/globals.yml

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NodeVersion)'

  - script: npm install autorest -g

  - template: /eng/pipelines/steps/cache-maven-repository.yml
    parameters:
      JobType: 'Fluent Integration'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(JavaVersion)
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'clean install'
      options: '$(DefaultOptions) -P local,testFluent -T 1C'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: fluentgen/target/site/test-coverage/jacoco.xml
      reportDirectory: fluentgen/target/site/test-coverage/
      failIfCoverageEmpty: false

  - template: /eng/pipelines/steps/cleanup-maven-local-cache.yml
