trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  NodeVersion: '18.x'

resources:
  repositories:
  - repository: azure-sdk-tools
    type: github
    name: Azure/azure-sdk-tools
    endpoint: azure
    ref: main
  - repository: azure-sdk-for-java
    type: github
    name: Azure/azure-sdk-for-java
    endpoint: azure
    ref: main

jobs:
- job: Generate_SDK

  timeoutInMinutes: 60

  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-tools
    fetchDepth: 1
  - checkout: azure-sdk-for-java

  - task: NodeTool@0
    displayName: 'Install Node.js $(NodeVersion)'
    inputs:
      versionSpec: '$(NodeVersion)'

#  - bash: |
#      npm install -g @typespec/compiler
#    displayName: 'Install autorest'

  - script: |
      python3 ./eng/sdk/sync_sdk.py --sdk-root=$(Build.SourcesDirectory)/azure-sdk-for-java --version=$(node -p -e "require('./typespec-extension/package.json').version")
    displayName: 'Generate SDK'
    workingDirectory: $(Build.SourcesDirectory)/autorest.java

  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
    parameters:
      PRBranchName: typespec-java-generation-$(Build.BuildId)
      CommitMsg: '[Automation] Generate SDK based on TypeSpec'
      PRTitle: '[Automation] Generate SDK based on TypeSpec'
      PRLabels: 'DPG'
      OpenAsDraft: 'true'
