trigger: none
pr: none

extends: 
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages: 
      - stage: Release

        jobs:
        - job: Build

          timeoutInMinutes: 30

          variables:
          - template: /eng/pipelines/variables/globals.yml
          - template: /eng/pipelines/variables/image.yml
          - name: buildArtifactsPath
            value: $(Pipeline.Workspace)/build_artifacts

          pool:
            name: $(LINUXPOOL)
            image: $(LINUXVMIMAGE)
            os: linux

          steps:
          - checkout: self
            submodules: true

          - task: NodeTool@0
            displayName: 'Install Node.js $(NodeVersion)'
            inputs:
              versionSpec: '$(NodeVersion)'

          - template: /eng/pipelines/steps/cache-maven-repository.yml
            parameters:
              JobType: 'Publish TypeSpec'

          - template: /eng/pipelines/templates/steps/maven-authenticate.yml

          - template: /eng/pipelines/templates/steps/npm-authenticate.yml

          - task: PowerShell@2
            retryCountOnTaskFailure: 1
            displayName: 'Build'
            inputs:
              pwsh: true
              filePath: Build-TypeSpec.ps1

          - task: PowerShell@2
            displayName: 'Get Package Version'
            inputs:
              targetType: 'inline'
              script: |
                $PACKAGE_VERSION = node -p -e "require('./typespec-extension/package.json').version"
                Write-Host("##vso[task.setvariable variable=PackageVersion]$PACKAGE_VERSION")

          - task: PowerShell@2
            displayName: 'Create GitHub Releases'
            inputs:
              filePath: eng/scripts/Create-Release.ps1
              arguments: >
                -releaseSha '$(Build.SourceVersion)'
                -tagName '@azure-tools/typespec-java_$(PackageVersion)'
                -title '@azure-tools/typespec-java_$(PackageVersion)'
                -releaseNotes '- Bug fix'
              pwsh: true
            timeoutInMinutes: 5
            env:
              GH_TOKEN: $(azuresdk-github-pat)

          - pwsh: |
              New-Item -ItemType Directory -Path "$(buildArtifactsPath)/packages" -Force
              Copy-Item -Path "./typespec-extension/*.tgz" -Destination "$(buildArtifactsPath)/packages"
            displayName: 'Copy packages to artifacts staging directory'

          # Always publish to internal feed
          - template: /eng/pipelines/templates/steps/create-authenticated-npmrc.yml
            parameters:
              npmrcPath: $(buildArtifactsPath)/packages/.npmrc
              registryUrl: https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-js/npm/registry/

          # publish to devops feed
          - pwsh: |
              $packageFiles = Get-ChildItem -Path . -Filter '*.tgz'
              foreach ($file in $packageFiles.Name) {
                Write-Host "npm publish $file --verbose --access public"
                npm publish $file --verbose --access public
              }
            displayName: Publish to DevOps feed
            workingDirectory: $(buildArtifactsPath)/packages

          # publish to npmjs.org
          - task: EsrpRelease@11
            displayName: 'Publish TypeSpec Java to NPM'
            inputs:
              ConnectedServiceName: Azure SDK PME Managed Identity
              ClientId: 5f81938c-2544-4f1f-9251-dd9de5b8a81b
              DomainTenantId: 975f013f-7f24-47e8-a7d3-abc4752bf346
              UseManagedIdentity: true
              KeyVaultName: kv-azuresdk-codesign
              SignCertName: azure-sdk-esrp-release-certificate
              Intent: PackageDistribution
              ContentType: npm
              FolderLocation: $(buildArtifactsPath)/packages
              Owners: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
              Approvers: ${{ coalesce(variables['Build.RequestedForEmail'], 'azuresdk@microsoft.com') }}
              ServiceEndpointUrl: https://api.esrp.microsoft.com
              MainPublisher: ESRPRELPACMANTEST

          - template: /eng/pipelines/steps/cleanup-maven-local-cache.yml
