trigger: none
pr: none

pool:
  name: "azsdk-pool-mms-ubuntu-2004-general"
  vmImage: "MMSUbuntu20.04"

jobs:
  - job: Build

    timeoutInMinutes: 30

    variables:
      - template: /eng/pipelines/variables/globals.yml

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - template: /eng/pipelines/steps/cache-maven-repository.yml
        parameters:
          JobType: 'Publish Autorest'

      - task: Maven@3
        displayName: 'Build JAR'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean install'
          options: '$(DefaultOptions) -P local -T 1C'
          mavenOptions: '$(MemoryOptions) $(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: Npm@1
        displayName: 'Install Dependencies for AutoRest Java'
        inputs:
          command: install

      - task: Npm@1
        displayName: 'Pack AutoRest Java'
        inputs:
          command: custom
          customCommand: pack

      - script: |
          npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          ls *.tgz | npm publish -0 --access public
          npm config delete //registry.npmjs.org/:_authToken
        displayName: 'Publish AutoRest Java to NPM'

      - template: /eng/pipelines/steps/cleanup-maven-local-cache.yml
