trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Build

    timeoutInMinutes: 30

    variables:
      JavaVersion: 1.11
      NodeVersion: '18.x'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NodeVersion)'
        inputs:
          versionSpec: '$(NodeVersion)'

      - task: Maven@3
        retryCountOnTaskFailure: 3
        displayName: 'Build JAR'
        inputs:
          mavenPomFile: pom.xml
          goals: 'clean install'
          options: '-P local,tsp -T 1C --no-transfer-progress'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false

      - task: Npm@1
        displayName: 'Install Dependencies for TypeSpec Java'
        inputs:
          command: install
          workingDir: ./typespec-extension

      - task: Npm@1
        displayName: 'Build TypeSpec Java'
        inputs:
          command: custom
          customCommand: run build
          workingDir: ./typespec-extension

      - task: Npm@1
        displayName: 'Lint TypeSpec Java'
        inputs:
          command: custom
          customCommand: run lint
          workingDir: ./typespec-extension

      - task: Npm@1
        displayName: 'Check-Format TypeSpec Java'
        inputs:
          command: custom
          customCommand: run check-format
          workingDir: ./typespec-extension

      - task: Npm@1
        displayName: 'Pack TypeSpec Java'
        inputs:
          command: custom
          customCommand: pack
          workingDir: ./typespec-extension

      - script: |
          npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          ls *.tgz | npm publish -0 --access public
          npm config delete //registry.npmjs.org/:_authToken
        displayName: 'Publish TypeSpec Java to NPM'
        workingDirectory: ./typespec-extension
