emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/cadl-output"
    partial-update: true
    namer: true
    generate-samples: false
    dev-options:
      generate-code-model: true
