arrowParens: always
trailingComma: es5
bracketSpacing: true
endOfLine: lf
printWidth: 100
semi: true
singleQuote: false
tabWidth: 2
plugins:
  - "./node_modules/@typespec/prettier-plugin-typespec/dist/index.js"
  - "./node_modules/prettier-plugin-organize-imports/index.js"
overrides:
  - files: "*.tsp"
    options:
      parser: typespec
