emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/tsp-output"
    partial-update: true
    generate-samples: true
    generate-tests: true
    examples-dir: "{project-root}/tsp/examples"
    flavor: "Azure"
    dev-options:
      generate-code-model: true
      loglevel: info
      debug: false
