emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/tsp-output"
    partial-update: true
    namer: true
    generate-samples: true
    generate-tests: true
    examples-directory: "{project-root}/tsp/examples"
    stream-style-serialization: true
    dev-options:
      generate-code-model: true
      support-versioning: true
      loglevel: info
