name: Pre-release @azure-tools/typespec-java
on:
  workflow_dispatch:
    inputs:
      version:
        description: release version
        required: true
      release_notes:
        description: release notes
        required: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "TAG_NAME=@azure-tools/typespec-java_$VERSION" >> $GITHUB_ENV
          echo "RELEASE_ARTIFACT=cadl-extension/azure-tools-typespec-java-$VERSION.tgz" >> $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and Package
        run: |
          mvn package -f pom.xml -P local,cadl --no-transfer-progress
          cd cadl-extension
          npm install
          npm run build
          npm run lint
          npm pack

      - name: Create Pre-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: ${{ github.event.inputs.release_notes }}

      - name: Upload Pre-release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.RELEASE_ARTIFACT }}
          asset_name: ${{ env.RELEASE_ARTIFACT }}
          asset_content_type: application/x-gtar
